// <auto-generated />
using System;
using MentalHealthApp.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentalHealthApp.DataAccess.Migrations
{
    [DbContext(typeof(MentalHealthAppContext))]
    [Migration("20220831073440_Notes Column")]
    partial class NotesColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IdentityUserIdentityRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("IdentityUserIdentityRole", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Adresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BlocScaraApartament")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodPostal")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sector")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StradaNumar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Adresa", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.CameraConferintum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<string>("OraInceput")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OraSfarsit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UtilizatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("CameraConferinta");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.ComentariiDiscutie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("continut");

                    b.Property<DateTime>("DataComentariu")
                        .HasColumnType("datetime")
                        .HasColumnName("dataComentariu");

                    b.Property<Guid>("DiscutieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscutieId");

                    b.HasIndex("UserId");

                    b.ToTable("ComentariiDiscutie", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Diagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Denumire" }, "UQ__Diagnost__19701A4F23232DD2")
                        .IsUnique();

                    b.ToTable("Diagnostic", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Discutie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("continut");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("datetime")
                        .HasColumnName("dataCreare");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titlu");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Discutie", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Entities.Valabilitate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("WorkDayId");

                    b.ToTable("Valabilitati");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Entities.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkDay");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfFailLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumberCountryPrefix")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("UserImage")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("AdresaId");

                    b.ToTable("IdentityUser", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityUserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTokenRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshTokenValue")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserToken", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityUserTokenConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("ConfirmationTypeId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserTokenConfirmation", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IstoricDiagnosticUtilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDiagnosticare")
                        .HasColumnType("datetime");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UtilizatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("IstoricDiagnosticUtilizator", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Programare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DataProgramare")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StareProgramare")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipProgramare")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UtilizatorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("Programare", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Simptome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Denumire" }, "UQ__Simptome__19701A4F05BDFAFB")
                        .IsUnique();

                    b.ToTable("Simptome", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Specialist", b =>
                {
                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialitate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("durataProgramare")
                        .HasColumnType("int");

                    b.HasKey("SpecialistId");

                    b.ToTable("Specialist", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Utilizator", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Asigurat")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Utilizator", (string)null);
                });

            modelBuilder.Entity("SimptomeDiagnostic", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SimptomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiagnosticId", "SimptomeId");

                    b.HasIndex("SimptomeId");

                    b.ToTable("SimptomeDiagnostic", (string)null);
                });

            modelBuilder.Entity("UtilizatorSimptome", b =>
                {
                    b.Property<Guid>("UtilizatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SimptomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UtilizatorId", "SimptomeId");

                    b.HasIndex("SimptomeId");

                    b.ToTable("UtilizatorSimptome", (string)null);
                });

            modelBuilder.Entity("IdentityUserIdentityRole", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Entities.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MentalHealthApp.Entities.CameraConferintum", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Specialist", "Specialist")
                        .WithMany("CameraConferinta")
                        .HasForeignKey("SpecialistId")
                        .IsRequired()
                        .HasConstraintName("FK_SpecialistIdConf");

                    b.HasOne("MentalHealthApp.Entities.Utilizator", "Utilizator")
                        .WithMany("CameraConferinta")
                        .HasForeignKey("UtilizatorId")
                        .IsRequired()
                        .HasConstraintName("FK_UtilizatorIdConf");

                    b.Navigation("Specialist");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.ComentariiDiscutie", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Discutie", "Discutie")
                        .WithMany("ComentariiDiscuties")
                        .HasForeignKey("DiscutieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Entities.IdentityUser", "User")
                        .WithMany("ComentariiDiscuties")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ComentariiDiscutie_User_UserId");

                    b.Navigation("Discutie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Discutie", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.IdentityUser", "User")
                        .WithMany("Discuties")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Discutie_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Entities.Valabilitate", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Specialist", "Specialist")
                        .WithMany("Valabilitati")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Entities.Entities.WorkDay", "WorkDay")
                        .WithMany("Valabilitati")
                        .HasForeignKey("WorkDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityUser", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Adresa", "Adresa")
                        .WithMany("IdentityUsers")
                        .HasForeignKey("AdresaId")
                        .IsRequired()
                        .HasConstraintName("FK_AdresaId");

                    b.Navigation("Adresa");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityUserToken", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.IdentityUser", "User")
                        .WithMany("IdentityUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityUserTokenConfirmation", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.IdentityUser", "User")
                        .WithMany("IdentityUserTokenConfirmations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IstoricDiagnosticUtilizator", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Diagnostic", "Diagnostic")
                        .WithMany("IstoricDiagnosticUtilizators")
                        .HasForeignKey("DiagnosticId")
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Entities.Utilizator", "Utilizator")
                        .WithMany("IstoricDiagnosticUtilizators")
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostic");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Programare", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Specialist", "Specialist")
                        .WithMany("Programares")
                        .HasForeignKey("SpecialistId")
                        .IsRequired()
                        .HasConstraintName("FK_SpecialistIdProg");

                    b.HasOne("MentalHealthApp.Entities.Utilizator", "Utilizator")
                        .WithMany("Programares")
                        .HasForeignKey("UtilizatorId")
                        .IsRequired()
                        .HasConstraintName("FK_UtilizatorId");

                    b.Navigation("Specialist");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Specialist", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.IdentityUser", "SpecialistNavigation")
                        .WithOne("Specialist")
                        .HasForeignKey("MentalHealthApp.Entities.Specialist", "SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpecialistId");

                    b.Navigation("SpecialistNavigation");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Utilizator", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.IdentityUser", "User")
                        .WithOne("Utilizator")
                        .HasForeignKey("MentalHealthApp.Entities.Utilizator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimptomeDiagnostic", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Diagnostic", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiagnosticSimptome_Diagnostic_DiagnosticId");

                    b.HasOne("MentalHealthApp.Entities.Simptome", null)
                        .WithMany()
                        .HasForeignKey("SimptomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiagnosticSimptome_Simptome_SimptomeId");
                });

            modelBuilder.Entity("UtilizatorSimptome", b =>
                {
                    b.HasOne("MentalHealthApp.Entities.Simptome", null)
                        .WithMany()
                        .HasForeignKey("SimptomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Entities.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UtilizatorSimptome_Utilizator_UserId");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Adresa", b =>
                {
                    b.Navigation("IdentityUsers");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Diagnostic", b =>
                {
                    b.Navigation("IstoricDiagnosticUtilizators");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Discutie", b =>
                {
                    b.Navigation("ComentariiDiscuties");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Entities.WorkDay", b =>
                {
                    b.Navigation("Valabilitati");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.IdentityUser", b =>
                {
                    b.Navigation("ComentariiDiscuties");

                    b.Navigation("Discuties");

                    b.Navigation("IdentityUserTokenConfirmations");

                    b.Navigation("IdentityUserTokens");

                    b.Navigation("Specialist")
                        .IsRequired();

                    b.Navigation("Utilizator")
                        .IsRequired();
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Specialist", b =>
                {
                    b.Navigation("CameraConferinta");

                    b.Navigation("Programares");

                    b.Navigation("Valabilitati");
                });

            modelBuilder.Entity("MentalHealthApp.Entities.Utilizator", b =>
                {
                    b.Navigation("CameraConferinta");

                    b.Navigation("IstoricDiagnosticUtilizators");

                    b.Navigation("Programares");
                });
#pragma warning restore 612, 618
        }
    }
}
